import clsx from 'clsx'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Salt Studios Design',
  description: 'Generated by create next app',
}

const devMode =
  process.env.NODE_ENV === 'development'

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body
        className={clsx(
          inter.className,
          devMode && 'debug-screens'
        )}
      >
        {children}
      </body>
    </html>
  )
}
